apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f vscode_server/docker-compose.yaml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: code-server
  name: code-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: code-server
status:
  loadBalancer: {}
